test:
#	mkdir -p generated/
#	sbt "run --targetDir generated --compile --test --genHarness --backend sysc"
	sbt "run --targetDir generated --compile --test --genHarness --backend sysc --design AddFilter"
	sbt "run --targetDir generated --compile --test --genHarness --backend sysc --design MyCounter"

SYSTEMC := /Users/jrl/noArc/clients/ucb/systemc/systemc-2.3.1
sysc:
	g++ AddFilter.cpp ../src/test/resources/AddFilterSysCdriver.cpp \
	   -I. -I$(SYSTEMC)/include -L$(SYSTEMC)/lib-macosx64 -lsystemc -o addfilter

.PHONY: test
