package Chisel

import scala.Predef._

/** This object was generated by sbt-buildinfo. */
case object BuildInfo {
  /** The value is "Chisel". */
  val buildInfoPackage: String = "Chisel"
  /** The value is "2.2.39". */
  val version: String = "2.2.39"
  /** The value is "2.10.6". */
  val scalaVersion: String = "2.10.6"
  /** The value is "0.13.16". */
  val sbtVersion: String = "0.13.16"
  /** The value is "2018-04-18 17:10:54.007". */
  val builtAtString: String = "2018-04-18 17:10:54.007"
  /** The value is 1524071454007L. */
  val builtAtMillis: scala.Long = 1524071454007L
  override val toString: String = {
    "buildInfoPackage: %s, version: %s, scalaVersion: %s, sbtVersion: %s, builtAtString: %s, builtAtMillis: %s" format (
      buildInfoPackage, version, scalaVersion, sbtVersion, builtAtString, builtAtMillis
    )
  }
}
