package Chisel

import scala.Predef._

/** This object was generated by sbt-buildinfo. */
case object BuildInfo {
  /** The value is "Chisel". */
  val buildInfoPackage: String = "Chisel"
  /** The value is "2.2.36". */
  val version: String = "2.2.36"
  /** The value is "2.11.7". */
  val scalaVersion: String = "2.11.7"
  /** The value is "0.13.11". */
  val sbtVersion: String = "0.13.11"
  /** The value is "2016-10-03 23:17:18.221". */
  val builtAtString: String = "2016-10-03 23:17:18.221"
  /** The value is 1475536638221L. */
  val builtAtMillis: scala.Long = 1475536638221L
  override val toString: String = {
    "buildInfoPackage: %s, version: %s, scalaVersion: %s, sbtVersion: %s, builtAtString: %s, builtAtMillis: %s" format (
      buildInfoPackage, version, scalaVersion, sbtVersion, builtAtString, builtAtMillis
    )
  }
}
